
package view;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;


public class MainScreenView extends javax.swing.JInternalFrame {

    /**
     * Creates new form WeatherDataFrame
     */
    public MainScreenView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnMenu = new javax.swing.JMenuBar();
        mnConfig = new javax.swing.JMenu();
        itemConfig = new javax.swing.JMenuItem();

        setTitle("Weather Data Display");

        mnConfig.setText("Configurar");

        itemConfig.setText("Abrir Configuração");
        mnConfig.add(itemConfig);

        mnMenu.add(mnConfig);

        setJMenuBar(mnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemConfig;
    private javax.swing.JMenu mnConfig;
    private javax.swing.JMenuBar mnMenu;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getItemConfig() {
        return itemConfig;
    }





    

}
