/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author W-E-R
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Principal() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ifPrincipal = new javax.swing.JInternalFrame();
        ifTimeData = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfHumidity = new javax.swing.JTextField();
        tfPressure = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        btInclude = new javax.swing.JButton();
        tfTemperature = new javax.swing.JTextField();
        ifLastUpdate = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txTemperature = new javax.swing.JLabel();
        txHumidity = new javax.swing.JLabel();
        txPressure = new javax.swing.JLabel();
        txDate = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        ifAverageData = new javax.swing.JInternalFrame();
        cbPeriod = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txTemperatureMed = new javax.swing.JLabel();
        txNumberRecordMed = new javax.swing.JLabel();
        txHumidityMed = new javax.swing.JLabel();
        txPressureMed = new javax.swing.JLabel();
        btExitMed = new javax.swing.JButton();
        ifRecords = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRecods = new javax.swing.JTable();
        brExitRecord = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        ifConfigure = new javax.swing.JInternalFrame();
        cbLog = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        mnMenu = new javax.swing.JMenuBar();
        mnConfig = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        ifPrincipal.setTitle("Weather Data Display");
        ifPrincipal.setVisible(true);

        ifTimeData.setTitle("Dados de tempo");
        ifTimeData.setVisible(true);

        jLabel1.setText("Temperatura");

        jLabel2.setText("Humidade");

        jLabel3.setText("Pressão");

        jLabel4.setText("Data");

        tfHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHumidityActionPerformed(evt);
            }
        });

        btInclude.setText("Incluir");
        btInclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncludeActionPerformed(evt);
            }
        });

        tfTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTemperatureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifTimeDataLayout = new javax.swing.GroupLayout(ifTimeData.getContentPane());
        ifTimeData.getContentPane().setLayout(ifTimeDataLayout);
        ifTimeDataLayout.setHorizontalGroup(
            ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifTimeDataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfHumidity)
                    .addComponent(tfPressure)
                    .addComponent(tfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(tfTemperature))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifTimeDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInclude, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        ifTimeDataLayout.setVerticalGroup(
            ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifTimeDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ifTimeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btInclude)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ifLastUpdate.setTitle("Ultima atualização de tempo");
        ifLastUpdate.setVisible(true);

        jLabel5.setText("Temperatura");

        jLabel6.setText("Humidade");

        jLabel7.setText("Pressão");

        jLabel8.setText("Data");

        txTemperature.setText("TEMPERATURA");

        txHumidity.setText("HUMIDADE");

        txPressure.setText("PRESSÃO");

        txDate.setText(" DD/MM/AAAA");

        btExit.setText("Fechar");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifLastUpdateLayout = new javax.swing.GroupLayout(ifLastUpdate.getContentPane());
        ifLastUpdate.getContentPane().setLayout(ifLastUpdateLayout);
        ifLastUpdateLayout.setHorizontalGroup(
            ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifLastUpdateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifLastUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        ifLastUpdateLayout.setVerticalGroup(
            ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifLastUpdateLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(txTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(txHumidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifLastUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btExit)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ifAverageData.setTitle("Dados médios");
        ifAverageData.setVisible(true);

        cbPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario", "Semanal", "Mensal" }));
        cbPeriod.setSelectedIndex(-1);

        jLabel9.setText("Periodo");

        jLabel10.setText("Temperatura");

        jLabel11.setText("Humidade");

        jLabel12.setText("Números de Registros");

        jLabel13.setText("Pressão");

        txTemperatureMed.setText("TEMPERATURA");

        txNumberRecordMed.setText("NRO REGISTROS");

        txHumidityMed.setText("HUMIDADE");

        txPressureMed.setText("PRESSÃO");

        btExitMed.setText("Fechar");
        btExitMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifAverageDataLayout = new javax.swing.GroupLayout(ifAverageData.getContentPane());
        ifAverageData.getContentPane().setLayout(ifAverageDataLayout);
        ifAverageDataLayout.setHorizontalGroup(
            ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifAverageDataLayout.createSequentialGroup()
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifAverageDataLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTemperatureMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNumberRecordMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txHumidityMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPressureMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifAverageDataLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExitMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ifAverageDataLayout.setVerticalGroup(
            ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifAverageDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTemperatureMed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txHumidityMed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txPressureMed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ifAverageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txNumberRecordMed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btExitMed)
                .addGap(15, 15, 15))
        );

        ifRecords.setTitle("Registro");
        ifRecords.setVisible(true);

        tbRecods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Temperatura", "Humidade", "Pressão"
            }
        ));
        jScrollPane1.setViewportView(tbRecods);

        brExitRecord.setText("Fechar");

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifRecordsLayout = new javax.swing.GroupLayout(ifRecords.getContentPane());
        ifRecords.getContentPane().setLayout(ifRecordsLayout);
        ifRecordsLayout.setHorizontalGroup(
            ifRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifRecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ifRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ifRecordsLayout.createSequentialGroup()
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brExitRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ifRecordsLayout.setVerticalGroup(
            ifRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifRecordsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ifRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(brExitRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        ifConfigure.setTitle("Configuração do Sistema");
        ifConfigure.setVisible(true);

        cbLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML" }));
        cbLog.setSelectedIndex(-1);
        cbLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLogActionPerformed(evt);
            }
        });

        jLabel14.setText("Log");

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifConfigureLayout = new javax.swing.GroupLayout(ifConfigure.getContentPane());
        ifConfigure.getContentPane().setLayout(ifConfigureLayout);
        ifConfigureLayout.setHorizontalGroup(
            ifConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifConfigureLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(cbLog, 0, 145, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifConfigureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ifConfigureLayout.setVerticalGroup(
            ifConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifConfigureLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ifConfigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSave)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mnConfig.setText("Configurar");
        mnMenu.add(mnConfig);

        ifPrincipal.setJMenuBar(mnMenu);

        javax.swing.GroupLayout ifPrincipalLayout = new javax.swing.GroupLayout(ifPrincipal.getContentPane());
        ifPrincipal.getContentPane().setLayout(ifPrincipalLayout);
        ifPrincipalLayout.setHorizontalGroup(
            ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ifLastUpdate)
                    .addComponent(ifTimeData))
                .addGap(58, 58, 58)
                .addGroup(ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifPrincipalLayout.createSequentialGroup()
                        .addComponent(ifAverageData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ifConfigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(ifPrincipalLayout.createSequentialGroup()
                        .addComponent(ifRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        ifPrincipalLayout.setVerticalGroup(
            ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ifAverageData)
                        .addComponent(ifTimeData))
                    .addComponent(ifConfigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(ifPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ifLastUpdate)
                    .addComponent(ifRecords))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ifPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ifPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncludeActionPerformed

    }//GEN-LAST:event_btIncludeActionPerformed

    private void tfTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemperatureActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExitActionPerformed

    private void tfHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHumidityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHumidityActionPerformed

    private void btExitMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExitMedActionPerformed

    private void cbLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLogActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brExitRecord;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btExitMed;
    private javax.swing.JButton btInclude;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbLog;
    private javax.swing.JComboBox<String> cbPeriod;
    private javax.swing.JInternalFrame ifAverageData;
    private javax.swing.JInternalFrame ifConfigure;
    private javax.swing.JInternalFrame ifLastUpdate;
    private javax.swing.JInternalFrame ifPrincipal;
    private javax.swing.JInternalFrame ifRecords;
    private javax.swing.JInternalFrame ifTimeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnConfig;
    private javax.swing.JMenuBar mnMenu;
    private javax.swing.JTable tbRecods;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfHumidity;
    private javax.swing.JTextField tfPressure;
    private javax.swing.JTextField tfTemperature;
    private javax.swing.JLabel txDate;
    private javax.swing.JLabel txHumidity;
    private javax.swing.JLabel txHumidityMed;
    private javax.swing.JLabel txNumberRecordMed;
    private javax.swing.JLabel txPressure;
    private javax.swing.JLabel txPressureMed;
    private javax.swing.JLabel txTemperature;
    private javax.swing.JLabel txTemperatureMed;
    // End of variables declaration//GEN-END:variables

    public JButton getBrExitRecord() {
        return brExitRecord;
    }

    public JButton getBtExit() {
        return btExit;
    }

    public JButton getBtExitMed() {
        return btExitMed;
    }

    public JButton getBtInclude() {
        return btInclude;
    }

    public JButton getBtRemover() {
        return btRemover;
    }

    public JButton getBtSave() {
        return btSave;
    }

    public JComboBox<String> getCbLog() {
        return cbLog;
    }

    public JComboBox<String> getCbPeriod() {
        return cbPeriod;
    }

    public JInternalFrame getIfAverageData() {
        return ifAverageData;
    }

    public JInternalFrame getIfConfigure() {
        return ifConfigure;
    }

    public JInternalFrame getIfLastUpdate() {
        return ifLastUpdate;
    }

    public JInternalFrame getIfPrincipal() {
        return ifPrincipal;
    }

    public JInternalFrame getIfRecords() {
        return ifRecords;
    }

    public JInternalFrame getIfTimeData() {
        return ifTimeData;
    }

    public JMenu getMnConfig() {
        return mnConfig;
    }

    public JMenuBar getMnMenu() {
        return mnMenu;
    }

    public JTable getTbRecods() {
        return tbRecods;
    }

    public JTextField getTfDate() {
        return tfDate;
    }

    public JTextField getTfHumidity() {
        return tfHumidity;
    }

    public JTextField getTfPressure() {
        return tfPressure;
    }

    public String getTemperatureValue() {
        return tfTemperature.getText();
    }

    public JLabel getTxDate() {
        return txDate;
    }

    public JLabel getTxHumidity() {
        return txHumidity;
    }

    public JLabel getTxHumidityMed() {
        return txHumidityMed;
    }

    public JLabel getTxNumberRecordMed() {
        return txNumberRecordMed;
    }

    public JLabel getTxPressure() {
        return txPressure;
    }

    public JLabel getTxPressureMed() {
        return txPressureMed;
    }

    public JLabel getTxTemperature() {
        return txTemperature;
    }

    public JLabel getTxTemperatureMed() {
        return txTemperatureMed;
    }

    public void setTxDate(JLabel txDate) {
        this.txDate = txDate;
    }

    public void setTxHumidity(JLabel txHumidity) {
        this.txHumidity = txHumidity;
    }

    public void setTxHumidityMed(JLabel txHumidityMed) {
        this.txHumidityMed = txHumidityMed;
    }

    public void setTxNumberRecordMed(JLabel txNumberRecordMed) {
        this.txNumberRecordMed = txNumberRecordMed;
    }

    public void setTxPressure(JLabel txPressure) {
        this.txPressure = txPressure;
    }

    public void setTxPressureMed(JLabel txPressureMed) {
        this.txPressureMed = txPressureMed;
    }

    public void setTxTemperature(JLabel txTemperature) {
        this.txTemperature = txTemperature;
    }

    public void setTxTemperatureMed(JLabel txTemperatureMed) {
        this.txTemperatureMed = txTemperatureMed;
    }

  
    
    
}
